#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://hats-drive.radrive29.workers.dev/ccache/hats/anci/ccache.tar.gz

cd /tmp

time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50 || time aria2c $url
time tar xf ccache.tar.gz
find ccache.tar.gz -delete

