#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -1 " -cf ccache.tar.gz ccache
}

time com ccache 1 # Compression level 1, its enough

if [ "$init_rclone" == "true" ]; then 
	time rclone copy ccache.tar.gz gdrive:ccache/hats/anci -P || rclone copy ccache.tar.gz gdrive:ccache/hats/anci -P
else
	mkdir -p ~/.config/rclone
	echo "$rclone_config" > ~/.config/rclone/rclone.conf
	time rclone copy ccache.tar.gz gdrive:ccache/nour/fluid -P
fi
